@extends('layouts.app-flowbite')

@section('title', 'Manajemen Pengguna')

@section('breadcrumb')
    @include('layouts.breadcrumb-flowbite', ['items' => [
        ['text' => 'Manajemen Pengguna', 'url' => '#']
    ]])
@endsection

@section('content')
    {{-- Main Card --}}
    <div class="bg-white border border-slate-100 rounded-2xl shadow-xl shadow-slate-200/50 dark:bg-gray-800 dark:border-gray-700">
        
        {{-- Card Header --}}
        <div class="p-6 border-b border-zinc-100">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h5 class="text-xl font-bold text-black dark:text-white tracking-tight">
                        <i class="bi bi-people me-2 text-blue-600"></i>Manajemen Pengguna
                    </h5>
                    <p class="text-sm text-zinc-600 mt-1">Kelola akses dan izin pengguna sistem</p>
                </div>
                
                <a href="{{ route('users.create') }}" class="text-sm font-semibold text-white bg-blue-700 hover:bg-blue-800 px-5 py-2.5 rounded-xl transition-all shadow-sm hover:shadow inline-flex items-center">
                    <i class="bi bi-person-plus me-2"></i>Tambah Pengguna
                </a>
            </div>
        </div>

        {{-- Info Alert --}}
        <div class="p-6 pb-0">
            <div class="flex items-start p-4 mb-4 text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400 border border-blue-100 dark:border-blue-900" role="alert">
                <i class="bi bi-shield-lock flex-shrink-0 w-5 h-5 me-3 mt-0.5"></i>
                <div>
                    <span class="font-bold block mb-1">Keamanan Sistem</span>
                    <div class="text-sm">
                        Kelola akses pengguna dengan bijak. Pastikan setiap pengguna memiliki role dan permissions yang sesuai dengan tanggung jawabnya.
                    </div>
                </div>
            </div>
        </div>

        {{-- Table Wrapper --}}
        <div class="p-6 pt-2 overflow-x-auto">
             <div class="relative overflow-x-auto">
                {{ $dataTable->table(['class' => 'w-full text-sm text-left text-gray-500 dark:text-gray-400'], true) }}
            </div>
        </div>
    </div>
@endsection

@push('page_styles')
    @include('includes.datatables-flowbite-css')
@endpush

@push('page_scripts')
    {!! $dataTable->scripts() !!}
    
    <script>
        $(document).ready(function() {
            // Apply Flowbite styles to DataTables elements generated by Buttons/Scripts
            
            // Custom Delete Confirmation
            $(document).on('click', '.btn-delete', function() {
                const userName = $(this).data('name') || 'Pengguna ini';
                const form = $(this).closest('form');
                
                Swal.fire({
                    title: 'Hapus Pengguna?',
                    html: `Pengguna <strong>"${userName}"</strong> akan dihapus permanen.<br><small class="text-gray-500">Tindakan ini tidak dapat dibatalkan!</small>`,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#E02424', // Red-600
                    cancelButtonColor: '#6B7280', // Gray-500
                    confirmButtonText: '<i class="bi bi-trash me-1"></i> Ya, Hapus!',
                    cancelButtonText: 'Batal',
                    reverseButtons: true,
                    background: document.documentElement.classList.contains('dark') ? '#1f2937' : '#ffffff',
                    color: document.documentElement.classList.contains('dark') ? '#ffffff' : '#000000',
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                });
            });
        });
    </script>
@endpush
